### ISSUE TITLE
Laravel 5 (4.3?)

### ISSUE THREAD

**Issue by energyaspects** [pixelfusion/ExpAuth#3]
How's the compatibility between this package and L5?

**Comment by tobz-nz** [comment]
I've not had a chance to try it yet.

**Comment by energyaspects** [comment]
Looks like on line 16 of ExpUserProvider.php there's an incompatability. The validateCredentials() method's first argument is a UserInterface $user, but the EloquentUserProvider expects a UserContract.

**Comment by tobz-nz** [comment]
ah, has the interface changed name? (I haven't even looked at the details of L5 yet - waiting until at least beta)

I'm more than happy to accept pull requests if you've got the time to look into it.

**Comment by energyaspects** [comment]
I'm extremely new to Laravel so I think this would be a very much out of my comfort zone. I've taken a quick look and it seems that I can switch the 'Interface' with Laravel 5's new UserContract instance but the next issue that triggers is

    Call to undefined method [package]

which looks like it's thrown from the ExpAuthServiceProvider on line 40:

    $this->package('Pixelfusion/ExpAuth');

Any ideas?

**Comment by tobz-nz** [comment]
Not yet sorry. I'll have to look into whats changed in setting up packages.
Taylor is working on the docs this week, so should have something to go by soon.

**Comment by energyaspects** [comment]
It's somewhat hacky, but I've managed to get this working in L5 using https://github.com/morrislaptop/LaravelFivePackageBridges to reimplement the package function in the framework (it was taken out in a previous commit).

Granted, this isn't a permanent solution (as things will no doubt continue to change before the beta) but it works. 

Here are the steps to get it working:

1) Install the LaravelFivePackageBridges pacakge
2) Create a new bridge for the ExpAuthServiceProvider (vendor/morrislaptop/laravel-five-package-bridges/src/Bridges):

* ExpAuthServiceProvider.php

```php
<?php namespace Morrislaptop\LaravelFivePackageBridges\Bridges;

use Pixelfusion\ExpAuth\ExpAuthServiceProvider as BaseExpAuthServiceProvider;
use Morrislaptop\LaravelFivePackageBridges\LaravelFivePackageBridgeTrait;

class ExpAuthServiceProvider extends BaseExpAuthServiceProvider {
    use LaravelFivePackageBridgeTrait;
}
```

3) Edit ExpAuthHasher.php

Change: 

`use Illuminate\Hashing\HasherInterface;` to `use Illuminate\Contracts\Hashing\Hasher as HasherInterface;`

4) Edit ExpUserProvider.php to use the new L5 Contract.

```php
<?php namespace Pixelfusion\ExpAuth;

use Illuminate\Auth\EloquentUserProvider;
use Illuminate\Contracts\Auth\Authenticatable as UserContract;

class ExpUserProvider extends EloquentUserProvider {

    /**
     * Validate a user against the given credentials.
     *
     * @param UserContract $user
     * @param  array $credentials
     * @return bool
     */
    public function validateCredentials(UserContract $user, array $credentials)
    {
        $hashedPassword = $user->getAuthPassword();

        // hash using the algo used for this password
        $byteSize = strlen($hashedPassword);

        return ! is_null($user) && $this->hasher->check($credentials['password'], $hashedPassword, array('salt' => $user->salt, 'byteSize' => $byteSize));
    }
}
```

**Comment by energyaspects** [comment]
Now that L5 is out officially, will you be updating your package?

**Comment by tobz-nz** [comment]
I'll have a look at it when I get a chance, but to be honest; its not going to be a priority.

I built it for a project at work where we're slowly migrating away from Expressionengine and needed a login method for a new laravel parts fo the system. 
We're now moved the login system to an oAuth provider and aren't using this package anymore.

If its an easy fix, I'll do it. Else I'll leave it up to someone else in need to pull request or fork it.

I'll try have a look into this week.

**Comment by drawmyattention** [comment]
We're in the same situation. There's an old clunky ExpressionEngine backend that all of the users are stored in but I really want to use Laravel for development going forward. 

From my code changes above, I got most of it working with L5 but I had a few issues with password resets. I'm still getting my head around Laravel however, so it may be an easy fix. Would appreciate you taking a look if you can.

**Comment by tobz-nz** [comment]
How did you get composer to install it in L5?

**Comment by drawmyattention** [comment]
I'll be releasing a brand new version of this that works with L5 out of the
box either later today or tomorrow.

**Comment by drawmyattention** [comment]
As promised, here is an Expression Engine authentication system for Laravel 5: https://github.com/drawmyattention/expauth 

Thanks to the original authoer for the initial code base.

**Comment by tobz-nz** [comment]
Sweet. I'll deprecate this one & mark as abandoned on packagist.
